services:
  auth-proxy:
    build:
      dockerfile: ./Dockerfile
      context: .
    environment:
      - "ALLOWED_IPS=172.21.0.1"
  app:
    image: strm/helloworld-http:latest
    #ports:
    #  - "8000:80"
    labels:
      traefik.enable: "true"
      traefik.http.routers.app.rule: "(Host(`app.localhost`))"
      traefik.http.middlewares.blocklist.forwardauth.address: "http://auth-proxy:8080/traefik"
      traefik.http.routers.app.middlewares: "blocklist"
    depends_on:
      - traefik
  traefik:
    image: traefik:latest
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - auth-proxy
